version: 2.1
jobs:
  build:
    docker:
      - image: cimg/node:20.3.1
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package-lock.json" }}
      - run: npm ci --legacy-peer-deps
      # - run: cd ./node_modules/protractor && npm i webdrivermanager@latest
      - save_cache:
          key: v1-dependencies-{{ checksum "package-lock.json" }}
          paths:
            - ~/.npm
      # - run: npm run style
      - run: npm run lint
      - run:
          name: Display Node.js version
          command: node -v
      - run: npm run build --configuration:production
      - run: npm run test:coverage --watch=false
      # - run: ng e2e
        orbs:
  # This Orb includes the following:
  # - checkout current repository
  # - npm install with caching
  # - start the server
  # - wait for the server to respond
  # - run Cypress tests
  # - store videos and screenshots as artifacts on CircleCI
  cypress: cypress-io/cypress@1
workflows:
  build:
    jobs:
      - cypress/run:
          start: npm start
          wait-on: 'http://localhost:4200'
          store_artifacts: true
      - run:
          name: Tar & Gzip compiled app
          command: tar zcf dist.tar.gz dist/local-weather-application
      - store_artifacts:
          path: dist.tar.gz
workflows:
  build-and-test:
    jobs:
      - build
