version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:lts-browsers
        - image: circleci/node:16.14
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package-lock.json" }}
      - run: npm ci
      # - run: cd ./node_modules/protractor && npm i webdrivermanager@latest
      - save_cache:
          key: v1-dependencies-{{ checksum "package-lock.json" }}
          paths:
            - ~/.npm
      - run: npm run style
      - run: npm run lint
      - run:
          name: Display Node.js version
          command: node -v
      - run: npm run build --configuration:production
      - run: npm run test:coverage -- --watch=false
      - run: npm run e2e
      - run:
          name: Tar & Gzip compiled app
          command: tar zcf dist.tar.gz dist/local-weather-app
      - store_artifacts:
          path: dist.tar.gz
workflows:
  build-and-test:
    jobs:
      - build
